version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www
    ports:
      - "9000"
    #   - "8000:8000"
    #   - "80:80"
    # command: "php /var/www/resolucao-oitimizada-1.php"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
    ports:
      - "8008:80"
      - "443:443"
